blog/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('<slug:pk>/', views.article),
    path('', views.index)
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from mysite import views
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('blog/', include('blog.urls')),
    path('login/', views.Login.as_view()),
    path('logout/', LogoutView.as_view()),
    path('signup/', views.signup),
]

blog/models.py
from django.db import models

class Article(models.Model):
    title = models.CharField(default="", max_length=30)
    text = models.TextField(default="")
    auther = models.CharField(default="", max_length=30)
    create_at = models.DateField(auto_now_add=True)
    update_at = models.DateField(auto_now=True)

mysite/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser
 
class UserManager(BaseUserManager):
 
    def create_user(self, email, password=None):
        if not email:
            raise ValueError('Users must have an email address')
        user = self.model(
            email=self.normalize_email(email),
        )
        user.set_password(password)
        user.save(using=self._db)
        return user
 
    def create_superuser(self, email, password=None):
        user = self.create_user(
            email,
            password=password,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user
 
class User(AbstractBaseUser):
    email = models.EmailField(
        max_length=255,
        unique=True,
    )
 
    is_active = models.BooleanField(default=True)
 
    is_admin = models.BooleanField(default=False)
 
    objects = UserManager()
 
    USERNAME_FIELD = 'email'
 
    REQUIRED_FIELDS = []
 
    def __str__(self):
        return self.email
 
    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True
 
    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True
    
    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

mysite/forms.py
from django import forms
from django.contrib.auth import get_user_model
 
class UserCreationForm(forms.ModelForm):
    password = forms.CharField()
 
    class Meta:
        model = get_user_model()
        fields = ('email',)
    
    def clean_password(self):
        password = self.cleaned_data.get("password")
        return password
 
    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

blog/views.py
from django.shortcuts import render
from blog.models import Article
from django.core.paginator import Paginator

def index(request):
    objs = Article.objects.all()
    paginator = Paginator(objs, 1)
    page_number = request.GET.get('page')
    context = {
        'page_obj': paginator.get_page(page_number),
        'page_number': page_number,
    }
    return render(request, 'blog/blogs.html', context)

def article(request, pk):
    obj = Article.objects.get(pk=pk)
    context = {
        'article': obj
    }
    return render(request, 'blog/article.html', context)


mysite/views.py
from django.shortcuts import render
from blog.models import Article
from django.contrib.auth.views import LoginView
from mysite.forms import UserCreationForm


def index(request):
    objs = Article.objects.all()[:3]
    context = {
        'titele': 'Really Site',
        'articles': objs,
    }

    return render(request, 'mysite/index.html', context)


class Login(LoginView):
    template_name = 'mysite/login.html'

def signup(request):
    context = {}
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            



templates/blog/article.html
{% extends 'mysite/base.html' %}
 
{% block content %}

<main class="container">
    <div class="row">
        <div class="col-md-8">
            <h3 class="pb-4 font-italic border-bottom">
                {{article.title}}
            </h3>
            <p class="small text-muted text-right">{{article.create_at}} {{article.auther}}</p>
            <p>{{article.text}}</p>
        </div>

        {% include 'mysite/snippets/sidebar.html' %}

    </div>
</main>
 
<footer class="border-top py-5 text-center bg-light mt-4">
    <p>
        <a href="/">トップに戻る</a>
    </p>
</footer>
 
{% endblock %}

templates/blog/blogs.html
{% extends 'mysite/base.html' %}
 
{% block content %}
 
<div class="container">
    <header class="py-3">
        <div class="row flex-nowrap justify-content-center align-item-center">
            <div class="col-4 text-center">
                <h1 class="display-4 font-italic">ReallySite</h1>
            </div>
        </div>
    </header>
    <div class="py-1 mb-2">
        <nav class="nav d-flex justify-content-between">
            <a class="p-2 link-secondary" href="#">ブログ</a>
            <a class="p-2 link-secondary" href="#">お問い合わせ</a>
            <a class="p-2 link-secondary" href="#">メニュー３</a>
        </nav>
    </div>
</div>
 
 
<main class="container">
    <div class="row">
        <div class="col-md-8">
            <h3 class="pb-4 font-italic border-bottom">
                Django Lesson
            </h3>


            {% for obj in page_obj %}
            <div class="blog-post">
                <h2 class="blog-post-title">{{ obj.title }}</h2>
                <p class="blog-post-meta">{{ obj.create_at }} by 
                    <a href="#">{{ obj.auther }}</a>
                </p>
                <p>{{ obj.text }}</p>
                <a href="/blog/{{obj.id}}" >
                    続きはこちらから
                </a>
                <hr>
            </div>
            {% endfor %}


            {% include 'mysite/snippets/pagination.html' %}
            

        </div>

        {% include 'mysite/snippets/sidebar.html' %}

    </div>
</main>
 

{% endblock %}

templates/mysite/base.html
<!doctype html>
<html lang="ja">
 
<head>
    {% include 'mysite/snippets/head.html' %}
</head>
 
<body>
    {% block content %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js"
        integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/"
        crossorigin="anonymous"></script>
</body>
 
</html>

templates/mysite/base_auth.html
<!doctype html>
<html lang="ja">
  <head>
        {% include 'mysite/snippets/head.html' %}
  </head>
  <body class="vh-100 d-flex align-items-center justify-content-center bg-light">
 
    {% block content %}
    {% endblock %}
    
  </body>
</html>

templates/mysite/index.html
{% extends 'mysite/base.html' %}
 
{% block content %}
 
<div class="container">
    <header class="py-3">
        <div class="row flex-nowrap justify-content-center align-item-center">
            <div class="col-4 text-center">
                <h1 class="display-4 font-italic">ReallySite</h1>
            </div>
        </div>
    </header>
    <div class="py-1 mb-2">
        <nav class="nav d-flex justify-content-between">
            <a class="p-2 link-secondary" href="/blog/">ブログ</a>
            <a class="p-2 link-secondary" href="#">お問い合わせ</a>
            <a class="p-2 link-secondary" href="#">メニュー３</a>
        </nav>
    </div>
    <div class="p-4 p-md-5 mb-4 rounded bg-warning">
        <div class="col-md-6 px-0">
            <h1 class="display-4 font-italic">Django講座</h1>
            <p class="lead my-3">文章をかこう</p>
            <p class="lead mb-0">
                <a href="#" class="font-weight-bold">続きを読む</a>
            </p>
        </div>
    </div>
    <div class="row mb-2">
        <div class="col-md-6">
            <div class="row g-0 border rounded overflow-hidden flex-md-row 
            mb-4 shadow-sm h-md-250 position-relative">
                <div class="col p-4 d-flex flex-column position-static">
                    <strong class="d-inline-block mb-2 text-primary">Django</strong>
                    <h3 class="mb-0">人気の記事</h3>
                    <div class="mb-1 text-muted">11/12</div>
                    <p class="card-text mb-auto">文章をかこう</p>
                    <a href="#" class="stretched-link">続きを読む</a>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="row g-0 border rounded overflow-hidden flex-md-row 
            mb-4 shadow-sm h-md-250 position-relative">
                <div class="col p-4 d-flex flex-column position-static">
                    <strong class="d-inline-block mb-2 text-primary">Django</strong>
                    <h3 class="mb-0">人気の記事</h3>
                    <div class="mb-1 text-muted">11/12</div>
                    <p class="card-text mb-auto">文章をかこう</p>
                    <a href="#" class="stretched-link">続きを読む</a>
                </div>
            </div>
        </div>
    </div>
</div>
 
 
<main class="container">
    <div class="row">
        <div class="col-md-8">
            <h3 class="pb-4 font-italic border-bottom">
                Django Lesson
            </h3>








            {% for obj in articles %}
            <div class="blog-post">
                <h2 class="blog-post-title">{{ obj.title }}</h2>
                <p class="blog-post-meta">{{ obj.create_at }} by 
                    <a href="#">{{ obj.auther }}</a>
                </p>
                <p>{{ obj.text }}</p>
                <a href="/blog/{{obj.id}}">
                    続きはこちらから
                </a>
                <hr>
            </div>
            {% endfor %}









            <nav class="blog-pagination">
                <a class="btn btn-outline-primary" href="/blog/">ブログ一覧</a>
            </nav>
        </div>

        {% include 'mysite/snippets/sidebar.html' %}


    </div>
</main>
 
<footer class="border-top py-5 text-center bg-light mt-4">
    <p>
        <a href="/">トップに戻る</a>
    </p>
</footer>
 
{% endblock %}

templates/mysite/login.html
{% extends 'mysite/base_auth.html' %}
 
{% block content %}

    {{req}}

<div class="container ">
    <div class="row">
        <div class="col-lg-3 m-auto ">
            <h1 class="display-4 font-italic text-center "><a href="/" class="text-decoration-none">ReallySite</a></h1>
            </div>
            <div class="col-lg-3 m-auto ">




            {% if user.is_authenticated %}
            ログイン中です
            {% else %}
            ログインしていません
            {% endif %}

            
            <form class="form-signin mx-4" method="POST">
                {% csrf_token %}
                <div class="text-center">
                    <h1 class="h5 my-4 ">ログイン</h1>
                </div>
 
                <div class="form-label-group my-3">
                    <input type="email" id="id_email" class="form-control" name="username" placeholder="Email address" required autofocus>
                </div>
 
                <div class="form-label-group my-3">
                    <input type="password" id="id_password" class="form-control" name="pasword" placeholder="Password" required>
                </div>
 
                <button class="btn btn-primary btn-block my-3" type="submit">サインイン</button>
 
            </form>




 
        </div>
    </div>
</div>
 
{% endblock %}

templates/mysite/snippets/head.html
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- Bootstrap CSS -->
<!-- レクチャー時点のalpha版を使用しています。betaや安定版を使用する場合はcssクラスが変更になっている可能性がありますので、適時修正してください -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css"
    integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">
<title>ReallySite</title>

templates/mysite/snippets/pagination.html

<nav class="blog-pagination">
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a class="btn btn-outline-primary" href="?page=1">&laquo; first</a>
                <a class="btn btn-outline-primary" href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
    
            {% if page_obj.has_next %}
                <a class="btn btn-outline-primary" href="?page={{ page_obj.next_page_number }}">next</a>
                <a class="btn btn-outline-primary" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>


    <a class="btn btn-outline-primary" href="#">古い記事</a>
    <a class="btn btn-outline-primary disabled" href="#">新しい記事</a>
</nav>


templates/mysite/snippets/sidebar.html
<aside class="col-md-4">
    <div class="p-4 mb-3 bg-light rounded">
        <h4 class="font-italic">
            ふじサンについて
        </h4>
        <p class="mb-0">ようこそMy講座へ！</p>
    </div>
</aside>